import { SlashCommandBuilder } from 'discord.js';

export default {
  data: new SlashCommandBuilder()
    .setName('explain')
    .setDescription('Explain what a channel is for')
    .addChannelOption((option) =>
      option
        .setName('channel')
        .setDescription('Which channel do you want explained?')
        .setRequired(true),
    ),

  async execute(interaction) {
    const channel = interaction.options.getChannel('channel');

    // List of channel IDs + explanations
    const explanations = {
      '1002715002244956280':
        'This is the place where you can talk in Albanian. In the Albanian channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '804789226020798475':
        'This is the place where you can talk in Arabic. In the Arabic channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1002721914768334848':
        'This is the place where you can talk in Cantonese. In the Cantonese channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1002716479600480306':
        'This is the place where you can talk in Czech. In the Czech channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1002722091239473202':
        'This is the place where you can talk in Danish. In the Danish channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '804791034030456852':
        'This is the place where you can talk in Dutch. In the Dutch channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '739913653373108276':
        'This is the place where you can talk in English. In the English channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '783679036081700944':
        'This is the place where you can talk in Filipino. In the Filipino channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '937823692489113611':
        'This is the place where you can talk in Finnish. In the Finnish channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '739913329539153950':
        'This is the place where you can talk in French. In the French channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '868623416591261716':
        'This is the place where you can talk in Greek. In the Greek channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '739913597064577084':
        'This is the place where you can talk in German. In the German channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1002720634830327808':
        'This is the place where you can talk in Hebrew. In the Hebrew channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1002716048509915146':
        'This is the place where you can talk in Hindi and Urdu. In the Hindi-Urdu channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1002719968611270667':
        'This is the place where you can talk in Hungarian. In the Hungarian channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1002721308590747731':
        'This is the place where you can talk in Icelandic. In the Icelandic channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '788488973080330300':
        'This is the place where you can talk in Italian. In the Italian channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '739913747459604540':
        'This is the place where you can talk in Japanese. In the Japanese channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '782981404954591293':
        'This is the place where you can talk in Korean. In the Korean channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '868623221530980362':
        'This is the place where you can talk in Latin. In the Latin channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1421546022240387072':
        'This is the place where you can talk in Lithuanian. In the Lithuanian channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1035995239736934502':
        'This is the place where you can talk in Malay and Indonesian. In the Malay-Indonesian channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '739913704199684156':
        'This is the place where you can talk in Mandarin. In the Mandarin channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '868623005931167785':
        'This is the place where you can talk in Norwegian. In the Norwegian channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '915638625801224222':
        'This is the place where you can talk in Polish. In the Polish channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '804792223887261727':
        'This is the place where you can talk in Portuguese. In the Portuguese channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '759520441642909736':
        'This is the place where you can talk in Romanian. In the Romanian channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '783678707436355594':
        'This is the place where you can talk in Russian. In the Russian channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1002712117675311184':
        'This is the place where you can talk in Serbo-Croat. In the Serbo-Croat channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '739913415522516992':
        'This is the place where you can talk in Spanish. In the Spanish channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '947762339774595084':
        'This is the place where you can talk in Swedish. In the Swedish channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1124230007829581897':
        'This is the place where you can talk in Thai. In the Thai channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1002711185965199501':
        'This is the place where you can talk in Turkish. In the Turkish channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1019870489184841748':
        'This is the place where you can talk in Ukrainian. In the Ukrainian channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
      '1279361929235791883':
        'This is the place where you can talk in Vietnamese. In the Vietnamese channel, you can practice with other learners and native speakers, ask questions, or just chat casually.\n\nIn each language channel, you’re welcome to talk in that language or in English, so don’t be shy to jump in at whatever level you’re comfortable with.\n\nAlso, be sure to check the pinned messages for any current events or activities you can participate in.\n\nLooking for a conversation starter? Send a message with !prompt to get a random subject!',
    };

    const explanation = explanations[channel.id] || 'No explanation found for this channel yet.';

    await interaction.reply({
      content: explanation,
      ephemeral: true,
    });
  },
};
